### ISSUE TITLE
Pry-theme adds 'm' to beginning of each line

### ISSUE THREAD

**Issue by sdla4ever** [kyrylo/pry-theme#46]
I added `gem 'pry-theme'` to my gemfile and then added the line `Pry.config.theme = "zenburn"` to a `.pryrc` in the rails root directory and now when i launch pry it shows the theme but it outputs a m before each line.

    [9] pry(main)> mtrue
    => mtrue
    [10] pry(main)> m44
    => m44

I am launching pry with `bundle exec pry -r config/envs`

**Comment by kyrylo** [comment]
You should update your Pry to the latest version. Let me know if it worked.

**Comment by sdla4ever** [comment]
That worked. :+1:
