### ISSUE TITLE
loosen requirement for json

### ISSUE THREAD

**Issue by dreyks** [kyrylo/pry-theme#48]
right now pry-theme depends on json gem 1.8, which does not compile under ruby 2.4-preview. There is a stable 2.0.1 release right now. The only backwards incompatibility it has is lack of support for ruby < 2.0. You could loosen the requirements to be `>= 1.8, < 3`

**Comment by kyrylo** [comment]
Perhaps there's no need to depend on that gem anymore because it's in stdlib. I'm also happy to drop support for <2.0. Feel free to send a PR.

**Comment by kyrylo** [comment]
Fixed by https://github.com/kyrylo/pry-theme/pull/49.
